
BY CLICKING THE &quot;Register&quot; BUTTON BELOW THIS AGREEMENT OR BY USING THE Photagious SERVICE (THE &quot;SERVICE&quot;), YOU AGREE TO THESE TERMS OF SALE (&quot;THE AGREEMENT&quot;) AND ALSO AGREE TO Photagious' TERMS AND CONDITIONS AND PRIVACY POLICY.
      <p>Copies of the <a href="/terms/">Terms of Use</a> and <a href="/privacy/">Privacy Policy</a> are available on the Photagious web site (the &quot;Site&quot;). </p>
      <p><strong>1. Service.</strong><br>        
      Photagious Membership. For your fee, Photagious hereby grants to you a license to use the following features and services during the term of you membership solely for your personal, non-commercial use of FotoUploader, FotoGuard, FotoBox, FotoLabels, Photagious Themes Library, Photagious Song Library, Foto Edit, FotoGames, Flix Editor, FotoGroups or any services rendered by the site. </p>
      <p><strong>2. Payments.</strong><br> 
      You agree to pay Photagious fees for the Service for the duration of time and the amount you selected on the select a membership page. You permit Photagious to charge this fee to your credit card and automatically renew the charge for the duration of your membership until you cancel. Photagious reserves the right to collect applicable taxes and impose surcharges for certain features of the Service.</p>
      <p><strong>3. Automatic Renewal and Cancellation.<br>
      </strong> Membership fees will be charged to your credit card and will automatically renew at the price then in effect for the duration of your membership until you cancel. Yearly memberships will automatically renew once a year and monthly memberships will automatically renew once a month. Cancellation of your membership can be done in the under my account in the update billing information section. If you choose to cancel, your cancellation will take effect at the end of the monthly or yearly term (depending on the billing cycle you chose) in which you cancelled. Upon cancellation, Photagious will delete your account the day after your monthly or yearly term has completed. If your credit card is invalid for any reason, charged back, or if Photagious does not receive payment, we will cancel your member benefits immediately.</p>
      <p><strong>4. Term.</strong> <br>
      Unless terminated earlier, this Agreement will remain in force as long as you are authorized to access the Service. If you terminate the Service, but continue to use Photagious as a free member(FotoGroup Visitor), the <a href="/terms/">Terms of Use</a> and<a href="/privacy/"> Privacy Policy</a> will still apply. </p>
      <p><strong>5. Refund Policy and Termination.</strong><br> 
      If Photagious cancels the entire Service, you may request a refund in writing within 30 days after the cancellation and receive a refund for the prorated amount of the fees for the Service. If Photagious makes a material adverse change to the Service or to the terms of this Agreement, you may terminate this Service and request a refund in writing within 15 days of such change and Photagious will refund the prorated amount of the fees for the Service. You may terminate the Service upon notice to Photagious at any time, but you are not allowed a refund of any portion of your fees for the Service except as otherwise expressly provided in this Section 4. Termination of this Agreement and the refund rights above are your sole remedies under this Agreement and against Photagious. If you are in violation to the <a href="/terms/">Terms of Use</a>, Photagious reserves the right to close all or any portion of the Site, deny you access and delete any files that you maintain on the Site and any information that you post and terminate your membership or all or any portion of the Service. </p>
      <p><strong>6. Representations, Warranties and Covenants.</strong><br> 
      You represent, warrant and covenant that (a) the membership and credit card information that you supply is true, correct and complete, (b) you will pay any charges that you incur in connection with the Service, including any applicable taxes, (c) you will update your membership and credit card information, (d) you will not allow anyone else to use your membership, (e) you will not transfer your membership or password to anyone else and (f) you will report to us any unauthorized or prohibited use of your membership or this Site. </p>
      <p><strong>7.Backup, Archiving Procedures. </strong><br/>
      Photagious provides automatic backup and redundancy services for your Fotos and all information related to our services including but not limited to Names, Descriptions, FotoBox and FotoGroup. <br>
        <br>
        By agreeing to this document, you understand the Photagious backup process and acknowledge our responsibilities as such:</p>
      <p> a)Daily onsite backups performed at 6:00am EST.<br>
          <br>
  b)Weekly offsite backups performed every Monday at 6:00am EST. </p>
      <p>As a Photagious Member, you agree that Photagious shall not be liable for any damages to your Fotos and/or related data arising from such causes beyond the direct and exclusive control of Photagious. You further acknowledge the liability for your own negligence. In no event shall Photagious be liable for any special or consequential damages. </p>
      <p><strong>8. Amendment.</strong> <br>
      Subject to the termination and refund rights above, you agree that Photagious reserves the right to amend this Agreement at any time, for any reason, and without notice. Any changes may be posted to the Site or sent to you by email or postal mail. </p>
      <p><strong>9. Third-Party Merchants.</strong> <br>
      The Site may offer you the ability to link to third-party web sites through this Site. All rules, policies and procedures of any third-party apply to you. Photagious is not responsible for information, goods or services provided by these third-parties and makes no representations or warranties about the goods or services available through third-parties. </p>
      <p><strong>10. Customer Data.</strong> <br>
      You grant Photagious and its third-party processor the right to use, reproduce, sublicense and distribute your transaction processing information (&quot;Customer Data&quot;) for purposes of processing your payment, screening customers and developing certain fraud prevention models. All Customer Data provided shall be subject to a written agreement of Photagious' third-party processor providing for the restriction on disclosure of any Customer Data to other third-parties except as necessary to perform the limited purposes under this section. </p>
      <p><strong>11. Legal Name, Address and Communications. Photagious, Inc. is located at 819 Eastland Drive, Villa Hills, KY 41017 USA.</strong> <br>
      You have the right to receive the legal name and address for Photagious at your email address by sending an email containing your email address and your request to support@Photagious.com. Official correspondence also may be sent via postal mail to Photagious, 819 Eastland Drive, Villa Hills, KY 41017 USA. Photagious reserves the right to forward email or postal communications to you for purposes of informing you of changes or additions to the Service or this Agreement. </p>
      <p><strong>12. Miscellaneous.</strong> <br>
    This Agreement will be governed and construed in accordance with the laws of the State of Kentucky, without regard to its conflict of laws provisions. Any legal suit, arbitration, action, mediation or proceeding arising out of or relating to this Agreement or the Service must be instituted in a state or federal court in Kenton County, Kentucky and you irrevocably submit to such jurisdiction. The <a href="/terms/">Terms of Use</a> and <a href="/privacy/">Privacy Policy</a> (a) apply to you, including, without limitation, the indemnification and limited liability provisions in the <a href="/terms/">Terms of Use</a> and (b) should be read in conjunction with this Agreement, so that nothing in this Agreement will serve to preempt the promises made in the  <a href="/terms/">Terms of Use</a> or <a href="/privacy/">Privacy Policy</a>. If any portion of this Agreement is deemed invalid or otherwise unenforceable, the remaining provisions shall remain in effect.</p>